Run tests in a loop and log result

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -103,7 +103,19 @@ jobs:
         # Ensure the SSH key is secure and log in to the VM
         $SSH_CMD 'sudo mkdir /mnt/hostshare && sudo mount -t 9p -o trans=virtio,version=9p2000.L hostshare /mnt/hostshare'
         # Execute each test file in the compiled directory of the repo
-        $SSH_CMD 'for test_file in /mnt/hostshare/compiled/*; do echo "Running $test_file"; timeout -s KILL 3 $test_file || echo "Test $test_file failed"; done'
+        $SSH_CMD <<'EOF'
+        for test_file in /mnt/hostshare/compiled/*; do
+            echo "Running $test_file"
+            bin="/mnt/hostshare/compiled/$test_file"
+            dir=$(mktemp -d)
+            (cd $dir && timeout -s KILL 3 $bin)
+            result=$?
+            rm -rf $dir
+            if [ $result -ne 0 ]; then
+                echo "Test $test_file failed"
+            fi
+        done
+        EOF
 
     - name: Display QEMU Serial Output
       if: always() # Ensure this step runs even if previous steps fail
